name: Approval Workflow
on:
    workflow_dispatch:
    push:
        branches:
            - develop
            - main
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            # - name: check GitHub context
            #   run: |
            #       echo "${{ toJson(github) }}"

            - name: check github.event_name
              run: echo "${{ github.event_name }}"

            - name: check github.event.ref
              run: echo "${{ github.event.ref }}"

    Build:
        needs: info
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Compile
              run: echo Compiling the App!

    DeployQA:
        name: Deploy to QA
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/develop'
        needs: Build
        runs-on: ubuntu-latest
        environment:
            name: QA
            url: 'http://qa.myapp.com'
        steps:
            - name: Deploy
              run: echo I am deploying to QA!

    DeployStaging:
        name: Deploy to Staging
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
        needs: Build
        runs-on: ubuntu-latest
        environment:
            name: STAGING
            url: 'https://staging.myapp.com'
        steps:
            - name: Deploy
              run: echo I am deploying to staging!

    DeployProd:
        name: Deploy to Prod
        needs: DeployStaging
        runs-on: ubuntu-latest
        environment:
            name: PROD
            url: 'https://myapp.com'
        steps:
            - name: Deploy
              run: echo I am deploying to prod!
