name: Matrix Workflow
on:
    workflow_dispatch:
        inputs:
            reason:
                description: here goes the reason for running the deploy
                required: true
jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm ci

            - name: Rechek node_modules
              run: ls

            - name: Build
              run: |
                   echo building the code...