name: Test Project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        -   name: Get Code
            uses: actions/checkout@v4
        -   name: List Node and Code
            run: |
                    node -v
                    ls
        -   name: Install NodeJS
            uses: actions/setup-node@v4
            with:
                node-version: 16
        -   name: Install Dependencies
            run: npm ci
        -   name: Rechek node_modules
            run: ls
        -   name: Output GitHub context
            run: echo "${{ toJson(github) }}"
        -   name: Run Test
            run: npm test