name: Test Project
on: [push, workflow_dispatch]       #events that trigger workflows(filters & activity types)
jobs:
  test:
    runs-on: ubuntu-latest        #workflow runners
    steps:
        -   name: Get Code
            uses: actions/checkout@v4       #workflow actions
        -   name: List Node and Code
            run: |
                    node -v
                    ls
        -   name: Install NodeJS
            uses: actions/setup-node@v4
            with:
                node-version: 16
        -   name: Install Dependencies
            run: npm ci
        -   name: Rechek node_modules
            run: ls
        -   name: Output GitHub context     # workflow context
            run: |
                echo "hey greetins from ${{ github.actor }}!"
                echo "${{ toJson(github) }}"
        -   name: Run Test
            run: npm test