name: Use Reusable workflow
on:
    workflow_dispatch:
jobs:
    build-test:
        runs-on: ubuntu-latest
        env:
          package-name: deployment-package
        steps:
            - name: Get Code
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm ci

            - name: Rechek node_modules
              run: ls

            - name: Build
              run: |
                   echo building the code...

            - name: Run Test
              run: npm test

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.package-name }}
                path: |
                    **.html
                    src/**/*
                    !src/**/**.test.js
                    !node_modules
                    !.github